version: '3'

services:
    server:
        restart: unless-stopped
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./data:/app/data"
        environment:
            Application__ConfigPath: ./data/config.yml